### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by ximagination80** [eligible/eligible-java#23]
Hi all,

I have next issue:

Handler processing failed; nested exception is java.lang.UnsupportedClassVersionError: com/eligible/exception/EligibleException : Unsupported major.minor version 52.0

In your documentation I read that java 7 is supported. 

Could you please help me with this?

ps. I can't use java 8

**Comment by ankitdimania-eligible** [comment]
Hi, Thanks for reporting the issue. We are investigating on the root cause.

**Comment by ankitdimania-eligible** [comment]
Pull request raised for fix. Pending code review.

**Comment by ankitdimania-eligible** [comment]
The fix has been released in version v1.7.0 of the library. Please check it out from maven or jcenter.

**Comment by ximagination80** [comment]
Hi, it works for me! Thank you
