### ISSUE TITLE
Build Failed in eclipse

### ISSUE THREAD

**Issue by ramganesh19** [eligible/eligible-java#28]
Hi, I checked out the master branch from github by import using eclipse. When try to import the project using Gradle Project and after build an eclipse project. I still keep getting below error message that VERSION file couldnt be found. But I do see the file with 1.8.1 version in the root folder.
Appreciate your help.
- What went wrong:
  A problem occurred evaluating root project 'eligible-java'.
  > VERSION (The system cannot find the file specified)

**Comment by ankitdimania-eligible** [comment]
Hi,
Thanks for reporting the issue. We are looking into the issue.

**Comment by ankitdimania-eligible** [comment]
Hi,

We do no officially support importing the project to Eclipse (yet) and we don't have any plans for this support.
We currently provide compiled jars directly to be used in client projects, and therefore, hope to reduce the burden to compile the project. The compiled jars are distributed through standard channels such as maven and jcenter. If you need access to downloadable jars, I'll be able to share the links with you.

If you still need to change somethings in the project, please feel free to share the usecase and we will assist you in getting it done.

Thanks,
Ankit Dimania

**Comment by ankitdimania-eligible** [comment]
Closing the issue. Please reopen if you need further assistance.
